# Generated by Erlang.mk. Edit at your own risk!

src/erldns.erl:: /Users/taavi/devel/rdns/apps/dns_erlang/include/dns_records.hrl /Users/taavi/devel/rdns/apps/dns_erlang/include/dns_terms.hrl include/erldns.hrl; @touch $@
src/erldns_axfr.erl:: /Users/taavi/devel/rdns/apps/dns_erlang/include/dns.hrl /Users/taavi/devel/rdns/apps/dns_erlang/include/dns_records.hrl /Users/taavi/devel/rdns/apps/dns_erlang/include/dns_terms.hrl; @touch $@
src/erldns_decoder.erl:: /Users/taavi/devel/rdns/apps/dns_erlang/include/dns_records.hrl /Users/taavi/devel/rdns/apps/dns_erlang/include/dns_terms.hrl; @touch $@
src/erldns_dnssec.erl:: /Users/taavi/devel/rdns/apps/dns_erlang/include/dns.hrl /Users/taavi/devel/rdns/apps/dns_erlang/include/dns_records.hrl /Users/taavi/devel/rdns/apps/dns_erlang/include/dns_terms.hrl include/erldns.hrl; @touch $@
src/erldns_doh_client.erl:: /Users/taavi/devel/rdns/apps/dns_erlang/include/dns_records.hrl /Users/taavi/devel/rdns/apps/dns_erlang/include/dns_terms.hrl include/erldns.hrl; @touch $@
src/erldns_edns.erl:: /Users/taavi/devel/rdns/apps/dns_erlang/include/dns_records.hrl /Users/taavi/devel/rdns/apps/dns_erlang/include/dns_terms.hrl; @touch $@
src/erldns_encoder.erl:: /Users/taavi/devel/rdns/apps/dns_erlang/include/dns_records.hrl /Users/taavi/devel/rdns/apps/dns_erlang/include/dns_terms.hrl; @touch $@
src/erldns_handler.erl:: /Users/taavi/devel/rdns/apps/dns_erlang/include/dns.hrl /Users/taavi/devel/rdns/apps/dns_erlang/include/dns_records.hrl /Users/taavi/devel/rdns/apps/dns_erlang/include/dns_terms.hrl include/erldns.hrl; @touch $@
src/erldns_query_throttle.erl:: /Users/taavi/devel/rdns/apps/dns_erlang/include/dns_records.hrl /Users/taavi/devel/rdns/apps/dns_erlang/include/dns_terms.hrl; @touch $@
src/erldns_records.erl:: /Users/taavi/devel/rdns/apps/dns_erlang/include/dns.hrl /Users/taavi/devel/rdns/apps/dns_erlang/include/dns_records.hrl /Users/taavi/devel/rdns/apps/dns_erlang/include/dns_terms.hrl include/erldns.hrl; @touch $@
src/erldns_recursive.erl:: /Users/taavi/devel/rdns/apps/dns_erlang/include/dns.hrl /Users/taavi/devel/rdns/apps/dns_erlang/include/dns_records.hrl /Users/taavi/devel/rdns/apps/dns_erlang/include/dns_terms.hrl include/erldns.hrl; @touch $@
src/erldns_resolver.erl:: /Users/taavi/devel/rdns/apps/dns_erlang/include/dns.hrl /Users/taavi/devel/rdns/apps/dns_erlang/include/dns_records.hrl /Users/taavi/devel/rdns/apps/dns_erlang/include/dns_terms.hrl include/erldns.hrl; @touch $@
src/erldns_storage_mnesia.erl:: /Users/taavi/devel/rdns/apps/dns_erlang/include/dns_records.hrl /Users/taavi/devel/rdns/apps/dns_erlang/include/dns_terms.hrl include/erldns.hrl; @touch $@
src/erldns_tcp_server.erl:: src/gen_nb_server.erl; @touch $@
src/erldns_txt.erl:: /Users/taavi/devel/rdns/apps/dns_erlang/include/dns_records.hrl /Users/taavi/devel/rdns/apps/dns_erlang/include/dns_terms.hrl /Users/taavi/devel/rdns/deps/proper/include/proper.hrl /Users/taavi/devel/rdns/deps/proper/include/proper_common.hrl include/erldns.hrl; @touch $@
src/erldns_worker.erl:: /Users/taavi/devel/rdns/apps/dns_erlang/include/dns.hrl /Users/taavi/devel/rdns/apps/dns_erlang/include/dns_records.hrl /Users/taavi/devel/rdns/apps/dns_erlang/include/dns_terms.hrl; @touch $@
src/erldns_worker_process.erl:: /Users/taavi/devel/rdns/apps/dns_erlang/include/dns.hrl /Users/taavi/devel/rdns/apps/dns_erlang/include/dns_records.hrl /Users/taavi/devel/rdns/apps/dns_erlang/include/dns_terms.hrl; @touch $@
src/erldns_zone_cache.erl:: /Users/taavi/devel/rdns/apps/dns_erlang/include/dns.hrl /Users/taavi/devel/rdns/apps/dns_erlang/include/dns_records.hrl /Users/taavi/devel/rdns/apps/dns_erlang/include/dns_terms.hrl include/erldns.hrl; @touch $@
src/erldns_zone_encoder.erl:: /Users/taavi/devel/rdns/apps/dns_erlang/include/dns.hrl /Users/taavi/devel/rdns/apps/dns_erlang/include/dns_records.hrl /Users/taavi/devel/rdns/apps/dns_erlang/include/dns_terms.hrl include/erldns.hrl; @touch $@
src/erldns_zone_parser.erl:: /Users/taavi/devel/rdns/apps/dns_erlang/include/dns.hrl /Users/taavi/devel/rdns/apps/dns_erlang/include/dns_records.hrl /Users/taavi/devel/rdns/apps/dns_erlang/include/dns_terms.hrl include/erldns.hrl; @touch $@
src/print_delegate.erl:: src/erldns_resolver.erl; @touch $@
src/sample_custom_handler.erl:: /Users/taavi/devel/rdns/apps/dns_erlang/include/dns.hrl /Users/taavi/devel/rdns/apps/dns_erlang/include/dns_records.hrl /Users/taavi/devel/rdns/apps/dns_erlang/include/dns_terms.hrl include/erldns.hrl; @touch $@
src/sample_custom_zone_encoder.erl:: /Users/taavi/devel/rdns/apps/dns_erlang/include/dns.hrl /Users/taavi/devel/rdns/apps/dns_erlang/include/dns_records.hrl /Users/taavi/devel/rdns/apps/dns_erlang/include/dns_terms.hrl include/erldns.hrl; @touch $@
src/sample_custom_zone_parser.erl:: /Users/taavi/devel/rdns/apps/dns_erlang/include/dns.hrl /Users/taavi/devel/rdns/apps/dns_erlang/include/dns_records.hrl /Users/taavi/devel/rdns/apps/dns_erlang/include/dns_terms.hrl include/erldns.hrl; @touch $@

COMPILE_FIRST += erldns_resolver gen_nb_server
